[project]
name = "cse-155-touchless-wm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mediapipe>=0.10.32",
    "opencv-python>=4.13.0.92",
    "pyautogui>=0.9.54",
]

[dependency-groups]
test = [
    "pytest>=8.0.0",
]
